FROM ubuntu:24.04

ARG USERNAME=ms-06s
ARG USER_UID=1000
ARG USER_GID=$USER_UID
ARG USER_HOME=/home/$USERNAME

# init setings of the os
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=ja_JP.UTF-8
ENV LC_ALL=ja_JP.UTF-8

# --- base minimum ---
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    locales \
    && locale-gen ja_JP.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

RUN if id -u $USER_UID >/dev/null 2>&1; then userdel -r $(id -un $USER_UID); fi \
    && groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && mkdir -p /etc/sudoers.d \
    && echo "$USERNAME ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# --- copy dotfiles ---
COPY . $USER_HOME/dotfiles

# --- install---
RUN bash $USER_HOME/dotfiles/packages/ubuntu.sh \
 && chown -R $USERNAME:$USER_GID $USER_HOME

# --- switch user ---
USER $USERNAME

RUN bash $USER_HOME/dotfiles/install.sh \
WORKDIR $USER_HOME

CMD ["/bin/bash", "-l"]
