# clipboard有効化
set -g set-clipboard on


# ==========================================
# 基本設定
# ==========================================
# マウス操作を有効にする (スクロールやペイン選択が可能に)
set -g mouse on

# 256色表示に対応
set -g default-terminal "tmux-256color"

# ステータスバーをトップに配置 (お好みで)
set -g status-position top

# デフォルトシェルを bash に設定
set-option -g default-shell /bin/bash

# \ で縦分割（カレントディレクトリを引き継いで bash を起動）
bind \\ split-window -h -c "#{pane_current_path}" /bin/bash

# - で横分割（カレントディレクトリを引き継いで bash を起動）
bind - split-window -v -c "#{pane_current_path}" /bin/bash
