set -g mouse on
set -g mode-keys vi
set -g default-terminal "tmux-256color"
set -g status-position top
set -g default-shell /bin/bash

set -g set-clipboard on
set -g allow-passthrough on

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line

bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi / send -X search-forward
bind -T copy-mode-vi ? send -X search-backward

# Enter で選択をコピーして抜ける（オプション）
bind -T copy-mode-vi Enter send -X copy-selection-andcancel

bind \\ split-window -h -c "#{pane_current_path}" /bin/bash

# - で横分割（カレントディレクトリを引き継いで bash を起動）
bind - split-window -v -c "#{pane_current_path}" /bin/bash
